---

language: node_js

node_js:
  - "lts/*"

sudo: required

dist: trusty

addons:
  chrome: stable
  
cache:
  directories:
    - "node_modules"

env:
  global:
    - JOBS=1

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
